### ISSUE TITLE
Add room constraints for non-rectangular rooms

### ISSUE THREAD

**Issue by timmercy** [meco-group/omg-tools#12]
Include safety distance as well

**Comment by rubenvanparys** [comment]
@timmercy : is there an example which illustrates non-rectangular room constraints? And could this be extended to 3d by adding a function get_hyperplanes in Polyhedron3D?

**Comment by timmercy** [comment]
There is not yet an example of non-rectangular room constraints, but I will provide one soon.

This is extendable to 3D I think, I will look at it.

**Comment by timmercy** [comment]
I added an example with an octagonal room.

**Comment by rubenvanparys** [comment]
I made the drawing of the room optional, by adding an extra boolean argument `draw` in the room dict (see p2p_holonomic_octroom).
