### ISSUE TITLE
Holonomic vehicle with orientation: regularization

### ISSUE THREAD

**Issue by timmercy** [meco-group/omg-tools#18]
It is possible to regularize on the change in orientation of the vehicle. For the examples I tested this was only necessary for the freeT problems. fixedT problems solved well without regularization.

For now there is an option which the user can set to regularize with a 1-norm or a 2-norm. He has to tune the weight himself. 

There are 2 issues here:
  - If you do a 1-norm regularization with weight 0 there are still constraints added, so while you would expect no change in behaviour there is really a change. 
  - If you do a regularization for the fixedT problem with a weight which is too high you reach the goal position, but not with the desired orientation.

**Comment by rubenvanparys** [comment]
You could check if the weight == 0.0 in order to add the constraints and 
part of the objective.

The second issue sounds natural as a trade-off is made between 'minimize 
change of orientation' and 'bring orientation to desired orientation'...

**Comment by timmercy** [comment]
Okay yes, that's maybe the most safe way to implement it then, I will push it like that.
