### ISSUE TITLE
Dubins car with fixedT end point not reached

### ISSUE THREAD

**Issue by timmercy** [meco-group/omg-tools#19]
Sometimes when you solve a fixedT problem with a Dubins car the end point is not exactly reached. E.g. the car goes to [3.0, 3.04] instead of [3.0, 3.0]. This only seems to happen when using the option 'ipopt.hessian_approximation': 'limited-memory'. 

What can we do about this?

**Comment by rubenvanparys** [comment]
Is safety_distance off? Is any other regularization off?

**Comment by timmercy** [comment]
No safety distance.
No other regularizations. 

Maybe this is due to the fact that you try to pull the vehicle towards the end point with the 1-norm? Compared to a holonomic vehicle, a Dubins car can't move perpendicular to its wheels anymore to correct the position at the end. But normally trajectory generated with this 1-norm objective should take that into account of course...

**Comment by timmercy** [comment]
What happens is that the end position is not reached exactly. Due to the nonholonomic nature of the AGV, bicycle and Dubins models, this is hard to correct. Correction would require maneuvering.

To solve this problem, we can just enlarge the vehicle's stop tolerance option. E.g. by default for the Dubins car this is:  self.options['stop_tol'] = 1.e-2

In some sense, this is reasonable, because the approach focuses on avoiding obstacles by using a receding horizon technique, not on reaching an endpoint with very high precision...
