### ISSUE TITLE
Error in room constraints

### ISSUE THREAD

**Issue by timmercy** [meco-group/omg-tools#20]
For now we only checked on the room being a square or a rectangle with 0 orientation. If this was the case we used the simple anti-collision constraints for the room. But this is not correct if you have a vehicle with a certain orientation. 

So the correct check is if: square or rectangular room, with 0 orientation, with tg_ha != BSpline --> simple anti-collision constraints, else: use hyperplanes

Note: when the vehicle has a circular shape e.g. a Dubins car, you can still use the simple variant of the room constraints while tg_ha is a BSpline. But maybe it is not worth adding this check?

**Comment by rubenvanparys** [comment]
I would do the check as: if shape is circle or ((shape is square or shape is rectangle) and orientation ==0): simple constraints

**Comment by timmercy** [comment]
Solved in commit 9f94eeb4e62f577effc1cccf5841ce9630590cc6
