### ISSUE TITLE
Decide which codes to run on travis

### ISSUE THREAD

**Issue by jgillis** [meco-group/omg-tools#3]
#2 brought us automated testing at every commit ( see [first green status](https://travis-ci.org/meco-group/omg-tools/builds/120957214) ).

Now we have to define which tests to run an add them to [travis.yml](https://github.com/meco-group/omg-tools/blob/cb5f39c12fca72fc102bf0ef624d0766d04f3b9b/.travis.yml#L19)
Apart from dedicated unittests, it make sense to run the examples.

However, `ufo.py` seems to take forever...

**Comment by rubenvanparys** [comment]
@jgillis Is there a way of installing the hsl solvers in travis?

**Comment by jgillis** [comment]
Yes, I can do that just like for casadi. Would this resolve the ufo problem?

**Comment by rubenvanparys** [comment]
Thanks. The problem in ufo (and in more example files) was due an 
infinite repeat of an animation at the end of the script.

**Comment by rubenvanparys** [comment]
Travis runs now all python files in /examples and also build exported c++ code and runs it.
