### ISSUE TITLE
Publishing videos?

### ISSUE THREAD

**Issue by jgillis** [meco-group/omg-tools#32]
The tests running on travis produces nice videos all the time.
Maybe we can publish them somewhere automatically?

**Comment by timmercy** [comment]
Good idea, we wanted to include figures or videos in the readme, but what you propose is more elegant! 
Is it possible to publish the travis output e.g. on the Github readme?

**Comment by jgillis** [comment]
Videos are not possible, in the readme; figures with a link, yes.
![test](https://cloud.githubusercontent.com/assets/329032/14735873/d959c9e0-0873-11e6-964e-aaade36b4e72.gif)

**Comment by jgillis** [comment]
We just need a place to host the resulting images..

**Comment by timmercy** [comment]
Maybe our personal KULeuven u-number page?

**Comment by gpipelee** [comment]
This could only be a temporary solution...
Maybe check with Armin where the videos for the MECO website are hosted...

**Comment by jgillis** [comment]
@asteinh ?

**Comment by asteinh** [comment]
Sorry, got stuck at https://github.com/meco-group/omg-tools/issues/32#issuecomment-213320670 for a few seconds ...

Two things:
- Videos of the MECO website are hosted on the [Youtube channel](https://www.youtube.com/channel/UCx6CCM-bq-Iz7n2uzx7JI2w) - but not indexed, so a user can't find them on Youtube
- I'm not sure how the personal websites work with LUNA, but I wouldn't rely on the MECH domain

**Comment by jgillis** [comment]
Okay, it doesn't make sense upload to youtube automatically after every commit.
Maybe gifs and imgur is an easy option

**Comment by jgillis** [comment]
Actually; I like the kuleuven webspace solution; what are the arguments against?

**Comment by gpipelee** [comment]
- On the long term I am in favor of solutions that remain and remain accessible even after people leave...
- I thought you were referring to the personal websites on the mech domain, which will most likely disappear soon...

**Comment by timmercy** [comment]
But the videos will be renewed after each commit, so actually they are not really permanent...
If the person which personal webspace we use would leave I guess Travis would give an error, such that we can select another page? But maybe this is indeed not really an elegant permanent solution.

**Comment by rubenvanparys** [comment]
Was there already an idea where we will put the website for promoting meco's software tools? (for which a job student would be hired). Maybe a good idea to put all meco's public data, videos,... at the same place.

Ruben

But the videos will be renewed after each commit, so actually they are not really permanent...
If the person which personal webspace we use would leave I guess Travis would give an error, such that we can select another page? But maybe this is indeed not really an elegant permanent solution.

-

**Comment by gpipelee** [comment]
For the time being let's start with putting them on a personal mech website, and keep on thinking about a sustainable solutions like a meco software website...

**Comment by rubenvanparys** [comment]
I will look how we can create animated gifs of the results. I suggest we start with publishing a selection of our most attractive videos. In fact we can place them just into a document folder on the repository?

**Comment by rubenvanparys** [comment]
I added a bunch of gif's to the readme.
