### ISSUE TITLE
Cleanup after run?

### ISSUE THREAD

**Issue by jgillis** [meco-group/omg-tools#33]
When I open an ipython shell and do
`run annoying_obstacle.py`
followed by
`run formation_holonomic.py`,

it behaves differently (ie crash), then when I run just `run formation_holonomic.py`.
Is there global params somewhere?

**Comment by rubenvanparys** [comment]
hmm this is not the expected behaviour... I will check this out.

**Comment by rubenvanparys** [comment]
voila!
