### ISSUE TITLE
Trailer: relaxed equality constraint

### ISSUE THREAD

**Issue by timmercy** [meco-group/omg-tools#35]
For now the trailer stays attached to the vehicle by stating that the change in orientation of the trailer is due to a velocity vector which acts on the trailer. This velocity vector comes from the vehicle. 

The relation between this velocity vector and a change in trailer orientation is one-to-one, but the equality constraint is relaxed to make the problem feasible.

Problem: the relaxation is done with some eps. For eps=1e-3 or higher you notice some oscillations in the trailer movement, if you make eps lower this behaviour disappears, but the vehicle doesn't reach its maximum velocity anymore. The lower eps is, the longer the movement takes.

- What is the explanation for this behaviour?
- Should we formulate this constraint in an alternative way? E.g. like  Goele proposed: put equality constraints on the position? The downside is that this less intuitive, the current constraint is more physical, i.e. a velocity vector pulling the trailer. And resembles the simulation and ode description to a greater extent.

**Comment by timmercy** [comment]
Explanation: the velocity of the vehicle is part of the relaxed equality constraint, so if the velocity is higher it is harder to satisfy the constraint. That's why the vehicle slows down, to make it easer to satisfy the constraint...

**Comment by rubenvanparys** [comment]
one major reason was due to issue #37.
