### ISSUE TITLE
AttributeError: 'Trailer' object has no attribute 'trajectories'

### ISSUE THREAD

**Issue by Sunshine352** [meco-group/omg-tools#60]
Trailor, Bicycle etc. object  has no attribute 'trajectories'

**Comment by rubenvanparys** [comment]
If no motion planning problem has been solved yet, this is indeed the case. A vehicle gets a 'trajectories' attribute after an initial motion problem is solved and is updated in subsequent motion updates. 

The idea is to extract the trajectories from the Simulator or Deployer. 

- From a Simulator you can extract trajectories and signals ([example](https://github.com/meco-group/omg-tools/blob/master/examples/tutorial_example.py#L138)). Trajectories are the computed trajectories for each update, signals are the simulated states and other physical values. When using the same model for simulation as optimization (which is the case by default), signals will have the same values as trajectories.
- From a Deployer you only extract trajectories (as this object should be used on a physical motion device), see example [here](https://github.com/meco-group/omg-tools/blob/master/examples/deployer_example.py#L82).

**Comment by Sunshine352** [comment]
Hi, rubenvanparys. I carefully look at tutorial_example, no difference is found between the example and p2p_trailor (p2p_bicycle, p2p_dubins etc.). However, tutorial_example has no problems like "object has no attribute 'trajectories" . May you further describe in detail ?

**Comment by rubenvanparys** [comment]
Are you running the example scripts as they appear on the repository? Did you install the [HSL linear solvers](https://github.com/casadi/casadi/wiki/Obtaining-HSL)? Can you check if commenting out [this line](https://github.com/meco-group/omg-tools/blob/master/examples/p2p_bicycle.py#L39) helps? If so, this means you don't have the ma57 solver (which is a bit faster than the default solver used by ipopt). I suspect this is the issue as tutorial_example is the only example that uses the default solver (which is installed if you have the casadi binary).

**Comment by Sunshine352** [comment]
When I comment out the line mentioned above,  no error appears.  Therefore,  the reason for this error is that I don't install HSL linear solvers. Thank you very much for your sparing time for my problem !
