### ISSUE TITLE
Register project on PyPI?

### ISSUE THREAD

**Issue by dvanthienen** [meco-group/omg-tools#61]
Hi all,

Related to easy integration of omg-tools with other Python or ROS projects, it could be of interest to upload omg-tools on PyPI.
PyPI (Python Package Index) works cf. creating a debian package for Linux, you can then easily install it with `pip install omg-tools`.
https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by jgillis** [comment]
Note that casadi has experimental support for pip now

**Comment by rubenvanparys** [comment]
omg-tools is registered on [PyPI](https://pypi.python.org/pypi/omg-tools#downloads) and is installed using `install pip omg-tools`!
