### ISSUE TITLE
Adapt for casadi 3.2

### ISSUE THREAD

**Issue by rubenvanparys** [meco-group/omg-tools#67]

**Comment by bellonemauro** [comment]
Hi,

I think this work is really nice and I wanted to try the tools. 
But I had a problem with casadi installing the omg-tools

        :~/code/omgTools$ sudo pip install omg-tools
Requirement already satisfied (use --upgrade to upgrade): omg-tools in /usr/local/lib/python2.7/dist-packages/omg_tools-0.1.3-py2.7.egg
Downloading/unpacking matplotlib2tikz (from omg-tools)
  Downloading matplotlib2tikz-0.6.14-py2.py3-none-any.whl
Downloading/unpacking casadi==3.1.1.post3 (from omg-tools)
  Could not find any downloads that satisfy the requirement casadi==3.1.1.post3 (from omg-tools)
Cleaning up...
No distributions at all found for casadi==3.1.1.post3 (from omg-tools)
Storing debug log for failure in /.pip/pip.log


then I have tried to install from the source using your script and running 
sudo python setup.py install

Installed /usr/local/lib/python2.7/dist-packages/omg_tools-0.1.3-py2.7.egg
Processing dependencies for omg-tools==0.1.3
Searching for casadi==3.1.1.post3
Reading https://pypi.python.org/simple/casadi/
No local packages or download links found for casadi==3.1.1.post3
error: Could not find suitable distribution for Requirement.parse('casadi==3.1.1.post3')


I hope you can help. 
Thanks
Mauro

**Comment by jgillis** [comment]
(CasADi maintainer here)
Here's the list of historic CasADi releases on PyPi:
https://pypi.org/project/casadi/#history

I don't recall if `3.1.1.post3` was ever public..

**Comment by rubenvanparys** [comment]
Hi Mauro,
Thank you for your interest in our toolbox!
Could you specify your setup (Windows/Linux/Mac?) and Python version.
Can you successfully perform `sudo pip install casadi` ?

Kind regards,
Ruben

**Comment by bellonemauro** [comment]
Hi, 

thanks for your answer.
I am now running ubuntu 14.04 64bit and python 2.7  .... and no install casadi does not work 

Downloading/unpacking casadi
  Could not find any downloads that satisfy the requirement casadi
Cleaning up...
No distributions at all found for casadi

am I missing some link in the list where pip looks for packages?
Thanks
M.

**Comment by jgillis** [comment]
Could you run `pip` with verbose flag `-v`?

**Comment by bellonemauro** [comment]
:~/code/omgTools$ sudo pip -v install casadi
Downloading/unpacking casadi
  Could not find any downloads that satisfy the requirement casadi
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for casadi
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for casadi

Storing debug log for failure in /home/mauro_veas/.pip/pip.log

**Comment by timmercy** [comment]
What is your pip version? We could re-create this problem, and it seems that it has to do something with the pip version. If your pip version is below 8.1, could you try to update it, and try again to install omg-tools?

Thank you for informing us about this problem!

**Comment by bellonemauro** [comment]
Thanks for your support, the problem with the version was caused by the fact that I have more than one version of python in my system. 
Running : 

sudo python -m pip install omg-tools

solved the problem. 

Thanks
Mauro

**Comment by timmercy** [comment]
About updating pip, you could use option1 mentioned here: https://stackoverflow.com/questions/38268074/how-should-i-upgrade-pip-on-ubuntu-14-04

**Comment by bellonemauro** [comment]
for your information: 

when I run the installation from the file (instead of using pip install) it still gives the problem.

Clearly, I now have the casadi package, but for some reason it is not found. 
If I comment the line 29 :         'casadi == 3.1.1.post3',     in the install_requires command,
it works (but clearly it is not checking if the package is there). 

In this case it should automatically install the new package but I do not know the specific command that runs in that specific situation, so it goes looking for the old pip package. 

Cheers
Mauro
