### ISSUE TITLE
Is it possible that I transplant the source code to a real P3DX robot?

### ISSUE THREAD

**Issue by wangfuan** [meco-group/omg-tools#68]
I have a robot with two wheels and a lidar, running ROS. How can I use your source code to navigate my robot?

**Comment by rubenvanparys** [comment]
Hey @wangfuan, thanks for your checking out our toolbox. I would suggest to take a look at our [ros example](https://github.com/meco-group/omg-tools/tree/master/examples/ros_example). If you have further questions, please ask.
