### ISSUE TITLE
Missing install instructions

### ISSUE THREAD

**Issue by jgillis** [meco-group/omg-tools#70]
Since CasADi 3.1 doesn't ship its own libgfortran dependency, 'libgfortran3' needs to be installed on the target. Perhaps useful to mention this on the front page?

**Comment by timmercy** [comment]
Maybe it's easier to include this in the required packages directly as: 

`sudo apt-get install python-pip python-numpy python-scipy python-matplotlib libgfortran3`?

**Comment by jgillis** [comment]
Bumped to casadi>=3.3 -> libfortran dependency not needed anymore
