### ISSUE TITLE
Accessing predicted trajectory at each step of simulation

### ISSUE THREAD

**Issue by iraikov** [meco-group/omg-tools#76]
Hello, thank you for creating omg-tools. I'd like to interface the omg simulator with another program (spiking neural networks simulator) for the purposes of comparing a trajectory generated by a neural network with the optimal trajectory generated by omg-tools. I was wondering whether the step function of the omg simulator is appropriate to call for this purpose, and how to access the predicted path for a vehicle (i.e. the path that has not been traveled yet). Thanks and best regards.

**Comment by rubenvanparys** [comment]
Good morning! Yes that's possible. Take a look at this example in which we explicitly write the feedback loop and access the computed trajectories each cycle: examples/deployer_example.py

**Comment by iraikov** [comment]
This is perfect, thank you!
