### ISSUE TITLE
Obstacle avoidance error in tutorial_example.py

### ISSUE THREAD

**Issue by heguohao0728** [meco-group/omg-tools#77]
Hi! Thanks for providing omg-tools! I'm new in vehicle path planning and obstacle avoidance. I have read all of your codes, it's really great! But when I try to run tutorial_example.py, some errors happened.
When I run this file with its original setting, it works fine. But when I changed some parameters, it worked like the screenshot below:
![screenshot1](https://user-images.githubusercontent.com/54935494/71463784-83801680-27f2-11ea-8611-a2dafd58f37a.png)
Could you tell me why this happened and how to solve it?
Really appreciated!

**Comment by heguohao0728** [comment]
Hello, professor! If this wrong is too simple but too hard or complicated to explan it, please tell me which part of the code I must pay attention. Thank you so much!

**Comment by timmercy** [comment]
Hello!

Is the horizontal rectangle a moving obstacle? Could you post your adapted code?

**Comment by heguohao0728** [comment]
Thanks! The rectangle is not a moving obstacle!

This problem always happened when I ran the code on my computer.
For example:
In tutorial_example.py, when I change the initial conditions of the vehicle like below:
**original code**
`vehicle.set_initial_conditions([-1.5, -1.5])`
**updated code**
`vehicle.set_initial_conditions([1., -1.5])`
and the error will show like below:
![sc](https://user-images.githubusercontent.com/54935494/71709724-d893dc00-2e33-11ea-973d-c47e15d3d003.png)

This is one situation, and the problem I raised in Dec. 2019 is another situation. In that case, I only change the position of a static obstacle.

**Comment by rubenvanparys** [comment]
Hi, does the terminal output say 'Infeasible problem detected'?

Op vr 3 jan. 2020 07:22 schreef heguohao0728 <notifications@github.com>:

**Comment by heguohao0728** [comment]
oh, Yes! It shows at the beginning. But why? I mean...this is a very simple room...

**Comment by rubenvanparys** [comment]
Yes, but note it is a highly non-convex problem... Sometimes it occurs no solution is found... You could try to use a scheduler problem that tries to overcome the non-convexity difficulty by using a simple global planner, and optimizing locally. See e.g. https://github.com/meco-group/omg-tools/blob/master/examples/schedulerproblem_example1.py

**Comment by rubenvanparys** [comment]
paper: https://lirias2repo.kuleuven.be/rest/bitstreams/484961/retrieve

**Comment by heguohao0728** [comment]
Thanks for your advice! I'll learn this paper and atfer that I will try it myself!
