### ISSUE TITLE
Unable to run examples dependent on HSL solvers.

### ISSUE THREAD

**Issue by abhayraw1** [meco-group/omg-tools#83]
I followed the instructions given in the readme.
I did download and install HSL following the instruction given [here](https://github.com/casadi/casadi/wiki/Obtaining-HSL)

![image](https://user-images.githubusercontent.com/14311538/86848756-34ce0600-c0cc-11ea-9dd8-81ed83e188ed.png)

When I try running an example that is dependent on the HSL solver, I get the following error:
`Could not find ma57 (from hsl library), which is needed for the code to run.`

Any pointers would be really appreciated!

**Comment by Shantnu12345** [comment]
I am facing the same issues. Is there a way to run these without hsl because for me performance is not a concern.

**Comment by timmercy** [comment]
@Shantnu12345: Yes, you can remove  `'ipopt.linear_solver': 'ma57'` from the problem options, then you won't need to install the HSL solvers. But keep in mind that some examples will run very slowly or (in some rare cases) may not run at all when you don't have the HSL solvers.

@abhayraw1: I'm sorry, but I don't know what goes wrong there... Do you have any more information about what you already tried to solve the problem?

**Comment by abhayraw1** [comment]
@timmercy: The problem was that Ipopt wasn't able to find ma57 for some reason.
I reinstalled the whole stack with updated versions and it worked!

I'll close this then. Thanks anyway ✌!

**Comment by nnop** [comment]
@abhayraw1 Met the same problem. May I ask how did you solve the problem?
