### ISSUE TITLE
Ill-posed problem detected: LBG[0] <= UBG[0] was violated. Got LBG[0] = nan and UBG[0] = nan.

### ISSUE THREAD

**Issue by parzival2** [meco-group/omg-tools#84]
Hi,

Great looking set of tools.
When I am trying to run an example, I am getting an error from Casadi that says

`RuntimeError: .../casadi/core/nlpsol.cpp:489: Assertion "lb <= ub && lb!=inf && ub!=-inf" failed:
Ill-posed problem detected: LBG[0] <= UBG[0] was violated. Got LBG[0] = nan and UBG[0] = nan.`

**How can it be reproduced**
- Install `omg-tools`
- Clone the example repository
- Run any example.

**Versions of packages**
Casadi - 3.5.2 (Is it too recent?) It was installed automatically while installing omg-tools
 **Update** 
Casadi - 3.4.1 and 3.5.1 works.
scipy - 1.2.3
omg-tools - 0.1.4

Can anybody let me what might be the problem that I have and how can it be solved? 

Thanks.

**Comment by jgillis** [comment]
Which example?

**Comment by parzival2** [comment]
Sorry for not mentioning the example in the description. I have tried with multiple ones and all resulted in the same error. 
The examples I have tried so far are 
- p2p_bicycle.py
- p2p_dubins.py
- platform_landing.py
- revolving_door.py

**Comment by jgillis** [comment]
And 3.5.1?

**Comment by parzival2** [comment]
Sorry for the delay. Just checked now. Casadi(3.5.1) works.

**Comment by jgillis** [comment]
Now fixed in CasADi 3.5.3
