### ISSUE TITLE
Build exported code from `formation_holonomic_export.py`

### ISSUE THREAD

**Issue by EnricaSo** [meco-group/omg-tools#86]
Hi!
Thank you for sharing this work, it's wonderful!

I'm trying to export the `formation_holonomic_export.py` example and build it to an executable, but I'm getting into some troubles. The export works properly: I get a folder `export_f` with the `src` code, the `instructions.txt` and a `Makefile`. 

In the `Makefile` I replace the content of these variables (where `***` is the path to where I cloned `omg-tools`):
```
CASADILIB = ***/omg-tools/venv/local/lib/python2.7/site-packages/casadi/casadi
CASADIINC = ***/omg-tools/venv/local/lib/python2.7/site-packages/casadi/include/
CASADIOBJ = ***/omg-tools/examples/export_f/bin/
```
Then, from the dir `export_f` I issue the command `make` and I get the following error:
```
In function `omgf::Point2Point::solve(double, std::vector<omgf::obstacle, std::allocator<omgf::obstacle> >&)':
Point2Point_omgf.cpp:(.text+0x2507): undefined reference to `casadi::Function::stats[abi:cxx11](int) const'
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'bin/FormationPoint2Point' failed
make: *** [bin/FormationPoint2Point] Error 1

```
If I go to the definition of `Point2Point::generateProblem()` I see that it requires `nlp.so` to be present in the path `CASADIOBJ`. However, in `CASADIOBJ` I have no such a file. I'm using `casadi 3.5.1` that I installed with `pip`.

Am I doing something wrong? Is there any other documentation for exporting c++ code from `omg-tools`?

Thank you in advance!

**Comment by jgillis** [comment]
Try with gcc-4

**Comment by EnricaSo** [comment]
I've just tried with gcc and  g++ version `4.9.3` and I get the same error.

**Comment by EnricaSo** [comment]
Hello!
It works out of the box with `python3.5`, `casadi3.5.1` and `g++4.9` (I was using `python2.7` above)

Thank you
