### ISSUE TITLE
Racetrack example stops after first iteration

### ISSUE THREAD

**Issue by Shantnu12345** [meco-group/omg-tools#87]
Could you please help me with this issue? Thank you for your time :) 

I am trying to run the gcodeproblem_racetrack.py example. However, it stops at first iteration and throws error as follows :

akashan@akashan:~/omg-tools/examples/GCode_examples$ python gcodeproblem_racetrack.py 
Do you want to shift or scale the loaded GCode? (yes/no): no

This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

elapsed time in get_init_guess  0.555369853973
Building nlp ...  in 1.788556 s
Current GCode block:  0
Invalid_Option

   It |      t upd  |       time 

   1 | 1.8392e-03 | 0.0000e+00 

/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py:2437: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)
Traceback (most recent call last):
  File "gcodeproblem_racetrack.py", line 87, in <module>
    deployer.update_segment()
  File "/home/akashan/omg-tools/omgtools/execution/deployer.py", line 168, in update_segment
    state_traj_old, input_traj_old, dinput_traj_old, ddinput_traj_old)
  File "/home/akashan/omg-tools/omgtools/execution/deployer.py", line 209, in check_results
    x1, y1, z1 = self.input_traj[:,-2]  # second last point
IndexError: index -2 is out of bounds for axis 1 with size 1

**Comment by timmercy** [comment]
The problem is in the "Invalid_Option" line. You have to remove the following line from the schedulerproblem.set_options function:  `'ipopt.linear_solver': 'ma57'`, since you don't have the MA57 solver installed.

Normally the problem should solve fine afterwards!

**Comment by Shantnu12345** [comment]
Thanks. I was able to install the hsl from source and it resolved the issue. Please note that hsl precomplied binaries never worked for me. I will close this issue. 

Best,
Shantnu
