### ISSUE TITLE
Asymmetric adjacency matrices

### ISSUE THREAD

**Issue by EnricaSo** [meco-group/omg-tools#90]
Hello,
It seems to me that asymmetric adjacency (or neighborhood) matrices are not supported for distributed formation problems. I'd like to add the support for it. Is there any theoretical reason on why it is missing for now? Should I keep anything in mind when doing it?
Thank you!

**Comment by rubenvanparys** [comment]
Hi, it's been more than 2 years I implemented this, so I'm not sure, but I think bi-directional interaction is an assumption for decoupling the problem. I refer to the paper:

Van Parys R., Pipeleers G. (2017), Distributed MPC for multi-vehicle systems moving in formation, Robotics and Autonomous Systems, vol. 97C (pp. 144-152).
