### ISSUE TITLE
Plots for deployer.py do not appear

### ISSUE THREAD

**Issue by padhupradheep** [meco-group/omg-tools#93]
Hey Guys, 

I was trying your example https://github.com/meco-group/omg-tools/blob/master/examples/deployer_example.py ! Apparently, I cannot see the plots that are being generated at the end of the code. 

I tried plt.show() but that did not help! Faced something similar?

**Comment by s18el05** [comment]
Hello,

I have similar issue with annoying_obstacle.py was the issue fixed for you? Please let me know if you have an idea

**Comment by s18el05** [comment]
Ok thank you I'll try to check that
