### ISSUE TITLE
Plot Issues

### ISSUE THREAD

**Issue by s18el05** [meco-group/omg-tools#95]
I have a plot issue trying to run this code, can anyone help me to solve this issue?

![image](https://user-images.githubusercontent.com/97359621/157919490-7aeffc3d-c628-4fde-bb72-e34e85b2009e.png)

![image](https://user-images.githubusercontent.com/97359621/157918836-9810c2e9-dc5f-4002-9b2c-e56c6f36005e.png)

**Comment by dzsonigg** [comment]
Hi @s18el05 !

We ran into this issue too. We checked installed packages (on two laptops) and found, that we need matplotlib==3.3.4. We had matplotlib==3.5.2, then "pip install matplotlib==3.3.4" and it solved the issue.

**Comment by s18el05** [comment]
@dzsonigg Thank you issue fixed for me as well

**Comment by s18el05** [comment]
@dzsonigg Thank you issue fixed for me as well
